### ISSUE TITLE
No way to modify MultiWindowConfig programatically

### ISSUE THREAD

**Issue by pmullot** [Nolanus/ngx-multi-window#20]
How can I change the values of MultiWindowConfig inside my code?

**Comment by Nolanus** [comment]
Just override the static properties in the `MultiWindowConfig` class.

This library is very similar to `ngx-page-scroll`, so you may check it's documentation for examples: https://github.com/Nolanus/ngx-page-scroll#configuration

**Comment by pmullot** [comment]
Thanks for answering so quick.
That's actually what I've done, but it doesn't seem to work.
I have to change the value of the timeout in the original npm package file.

**Comment by kayvanbree** [comment]
Maybe it would be better to use forRoot(myMultiWindowConfig) when importing the module. @Nolanus, are you still maintaining this project? I'd like to program this and create a pull request, but only if you are able to approve the request and publish a new version.

**Comment by Nolanus** [comment]
Hi @kayvanbree, yes, this module is still maintained, you're welcome to submit PRs for this change.

**Comment by kayvanbree** [comment]
Awesome, I'll work on it later this week.

**Comment by kayvanbree** [comment]
@Nolanus What's up with all the greenkeeper/rollup branches?

**Comment by Nolanus** [comment]
They get created as the current `rollup` dev-dependency constraint is only `^0.60.0`. Haven't tested it manually, is there a need to take the latest version of it to generate files compatible with the latest angular releases?

The build system should be moved to `ng-packagr` in some future anyway.

**Comment by kayvanbree** [comment]
You mean the new Angular 6 way of building libraries? I could do that. I'm having trouble running the demo anyway.

**Comment by Nolanus** [comment]
That'd be great. I'm very busy at the moment, so I can't tell when and if I would find in the next months (although it's probably mainly just generating the new structure and copy-pasting existing code).
I planned on using the [`generate library`](https://github.com/angular/angular-cli/wiki/generate-library) command of angular-cli for that. You're welcome to do this, I'll approve, merge and release it.

**Comment by kayvanbree** [comment]
I built some libraries since Angular 6. I'll create a PR for it.

**Comment by kayvanbree** [comment]
I created a PR (https://github.com/Nolanus/ngx-multi-window/pull/30). It's not finished yet, but I made the PR so you can see what I changed.

**Comment by Nolanus** [comment]
Closing this, as PR has been merged. Just updated the README on that
