### ISSUE TITLE
urlString in newWindow

### ISSUE THREAD

**Issue by Endettai** [Nolanus/ngx-multi-window#22]
Hi, There are any way to set correctly a StrignUrl to the new window? 
when i try to set the url i receive an error.

Thanks!

**Comment by Nolanus** [comment]
I can't tell why it's not working in your case, as you didn't share the error message or code you're using but you may find a working example in the demo application: https://github.com/Nolanus/ngx-multi-window/blob/master/demo/src/app/app.component.ts#L66
