### ISSUE TITLE
not working in IE11 Win8

### ISSUE THREAD

**Issue by Br85** [Nolanus/ngx-multi-window#23]
I can't send message with Win 8 IE 11. When I call getKnownWindows() in sender window it only sees itself.
it works fine in Firefox and Chrome.

**Comment by Nolanus** [comment]
Hi @Br85, you can inspect the local storage in the IE developer tools and check what the localstorage object contains.

Please note that there's a known issue about local storages not syncing properly in IE11 and some Edge versions (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110656/). To communicate across tabs/windows this is a necessity.
