### ISSUE TITLE
Persisting window names on refresh

### ISSUE THREAD

**Issue by kayvanbree** [Nolanus/ngx-multi-window#26]
It would be awesome if the name of a window persists on refreshing the page. Something like this:

```javascript
// Called in some Angular component
const name = window.name;

if (!name || name.indexOf('AppWindow') === -1) {
  window.name = this.multiWindowService.name;
  console.log('Saving window ID to session: ' + this.multiWindowService.name);
} else {
  this.multiWindowService.name = name;
  console.log('Got window ID from session storage: ' + this.multiWindowService.name);
}
```
If you do this and you refresh the page, ngx-multi-window creates a new variable in the localStorage, but it keeps using the old one. If this would be done in the library itself, it would probably mean you can use the same key of the localStorage without creating a new one. 

I also tried using the sessionStorage because I don't want to use window.name in case someone else uses it, but I got some security issues:

```javascript
const key = 'dock-panels-window-id';
    const name = window.sessionStorage.getItem(key);

    if (!name || name.indexOf('AppWindow') === -1) {
      window.sessionStorage.setItem(key, this.multiWindowService.name);
      console.log('Saving window ID to session: ' + this.multiWindowService.name);
    } else {
      this.multiWindowService.name = name;
      console.log('Got window ID from session storage: ' + this.multiWindowService.name);
    }
```

The error:
```
ERROR DOMException: Failed to execute 'getItem' on 'Storage': access is denied for this document.
    at DockRootComponent.push../projects/dock-panels/src/lib/components/dock-root/dock-root.component.ts.DockRootComponent.initializeWindowName (http://localhost:4200/main.js:670:42)
    at DockRootComponent.push../projects/dock-panels/src/lib/components/dock-root/dock-root.component.ts.DockRootComponent.ngOnInit (http://localhost:4200/main.js:685:14)
    at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.js:63483:19)
    at checkAndUpdateNodeInline (http://localhost:4200/vendor.js:64747:20)
    at checkAndUpdateNode (http://localhost:4200/vendor.js:64709:16)
    at debugCheckAndUpdateNode (http://localhost:4200/vendor.js:65342:38)
    at debugCheckDirectivesFn (http://localhost:4200/vendor.js:65302:13)
    at Object.eval [as updateDirectives] (ng:///AppModule/HomeComponent.ngfactory.js:14:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:4200/vendor.js:65294:21)
    at checkAndUpdateView (http://localhost:4200/vendor.js:64691:14)
```

**Comment by Nolanus** [comment]
Hi,

I also experimented with this feature when creating the library and faced similar issues with usage of `sessionStorage`. Including problems when the "duplicate tab" feature available in chrome, resulting in the `sessionStorage` to be cloned as well.

At the moment `window.name` is the only option I can think of for that... The developer of the site should be aware whether any other feature/plugin is utilizing this property for whatever purposes, so it should be ok (but it still remains a hacky approach).
I'll add an enhancement tag on this and will take a look at it once I find time, feel free to create a PR though.

**Comment by kayvanbree** [comment]
If I find a better way to do it than using `window.name` I'll create a PR. For now I am using `window.name` within my own application, hoping nobody uses the `window.name`, because there's some other things that need to be done first...

**Comment by kayvanbree** [comment]
@Nolanus Did you already implement this? 

I see you are opening a window something like this: `http://localhost:4200/?ngxmw_w_5am3m2nz1essu`. I don't know if using the query params would be the way to go for this. I'm afraid such an implementation will interfere with applications using the library. I'd like to hear your thoughts about that.

**Comment by Nolanus** [comment]
Not implemented yet. The current implementation passes the new window id as query parameter, but this is a different thing than keeping the current window's name on refresh.

**Comment by kayvanbree** [comment]
I can think of a couple of sub-optimal options:
- Maybe it would be better if its an actual key-value pair like this: `http://localhost:4200/?ngxmw_name=ngxmw_w_kl38sdfjkj`. That way everybody can just ignore the key `ngxmw_name` and focus on their own query parameters. You can read the query params from the `Router` or `ActiveRoute` (I'd have to check which one).
- In a project I'm using the `#` part of the url. I think that may be less common to use. This should probably be key-value too. 
- You could use `window.name` for that, but that's not a nice option either. It does seem to be empty most of the time. I really don't know the consequences of using `window.name` but I do know this works, because this is what I use on top of `ngx-multi-window` to persist my window names. 

The most common way would be to use the query parameter I quess. You can maximize compatibility by using a good key name.

**Comment by Nolanus** [comment]
Hi,

thank you for the ideas!
Regarding the key-value pair: whether the actual "data" is encoded in the value of a key-value pair or the presence of the key itself holds the data doesn't seem to make much of a difference.
Using `Router` or `ActivatedRoute` to extract the query parameters would
a) add a dependency on the angular router which might not be used by all angular apps, although probably all "larger" apps use it
b) it's not that easy to extract query params when having more complex apps (see https://github.com/angular/angular/issues/3957), although I haven't explicitly tried it in this libraries context

Regarding the HashRouterStrategy: This should be no problem, as one can combine hash values and query params in a url. The query parameter is only used on loading to read the "window id" used by this library and can be removed on the next angular router navigation. Please feel free to name a demo setup that would showcase the problem.

Regarding name saving: I just pushed a branch [feature/save-window-name](https://github.com/Nolanus/ngx-multi-window/tree/feature/save-window-name) with a first draft of that feature. You may test it and provide feedback!
