### ISSUE TITLE
not able to run demo app

### ISSUE THREAD

**Issue by roscoedeemarutam** [Nolanus/ngx-multi-window#31]
Hi, I have an issue when trying to run the demo app!

I cloned the git repository, then when I run the command 'npm run demo' in c:\gitrepos\ngx-multi-window

I get a lot of warnings and in the end a couple of errors before it goes back to the commandline.

![error multi window](https://user-images.githubusercontent.com/35805262/46953934-7ebcc000-d08f-11e8-8e20-24adebee603a.PNG)

not really sure what I'm doing wrong or what I'm missing here?! 

kind regards

**Comment by roscoedeemarutam** [comment]
hi there,

Nevermind the previous post! 
I just made a new angular app copied the code, npm'ed the ngx-multi-window and imported the multiwindowmodule. 
Now when I try to add a new window i get a message: "No Location Provider present". I assume it has something to do with the rollup.js part in the readme because I didn't do anything with that yet, because, and excuse my ignorance, i have no idea what to do. If someone could point me in a right direction here would be very much appreciated! 

kind regards

**Comment by Nolanus** [comment]
Hi,

sorry for the problems, but angular is changing rapidly making it hard for side projects to keep up-to-date.

This error is thrown if you call the `newWindow()` method to get help opening another/second window with the app. However, no [LocationProvider](https://angular.io/api/common/Location) is used in your angular app, meaning you're not using the "Routing" functionality.
Without that's it's not possible to read query parameters from the url the angular way. This means, the new window would be opened, but the angular app in that new window is not capable of reading the ngx-multi-window relevant query parameters. These query parameters are necessary in order for the new window to "know" what id it should use.

Solution: Either use Routing or just open a new window without calling `newWindow()` first.

**Comment by roscoedeemarutam** [comment]
adding the router works like a charm... thx!!

**Comment by kayvanbree** [comment]
I think this one can be closed?

**Comment by roscoedeemarutam** [comment]
yes, this one can be closed!!
