### ISSUE TITLE
Module build failed in Aangular 13 after upgrading from 0.3.2 to 0.4.0

### ISSUE THREAD

**Issue by ravipromact** [Nolanus/ngx-multi-window#89]
![Screenshot 2022-06-10 153946](https://user-images.githubusercontent.com/53940155/173043687-6ff3cbe1-c246-4a97-99ef-c8cf70b0fd32.png)
It says application depends upon a library published using Angular version 14.0.1
Please help!

**Comment by Nolanus** [comment]
Hi @ravipromact,
please check v0.4.1, which has been built with angular v7 again. Also consider updating the version constraint in your _package.json_ to `~0.4.1`, so you not download v0.5 which requires angular v14.

**Comment by ravipromact** [comment]
Thanks
